services:
  node:
    container_name: next-template-node
    build:
      context: ./.docker/node
    volumes:
      - ./:/usr/src
    command: /bin/bash -c "yarn && yarn dev"
    ports:
      - 3000:3000
    tty: true

  firebase:
    container_name: next-template-firebase
    build:
      context: ./.docker/firebase
    command: /bin/bash -c "firebase emulators:start"
    volumes:
      - ./firebase/emulators/:/opt/workspace:cached
      # - ./.firebaserc:/opt/firebase/.firebaserc
      # - ./firebase.json:/opt/firebase/firebase.json
      # - ./firestore.indexes.json:/opt/firebase/firestore.indexes.json
      # - ./firestore.rules:/opt/firebase/firestore.rules
      - ./firebase/bin/:/root/.cache:cached
      - ./firebase/config/:/root/.config:cached
      # - ./functions:/opt/firebase/functions
      # - ./extensions:/opt/firebase/extensions
    ports:
      - 9005:9005
      - 4000:4000
      - 5001:5001
      - 8080:8080
      - 9099:9099
    working_dir: /opt/workspace
    tty: true
