services:
  node:
    build: 
      context: ./.docker/node
    container_name: next-template-node
    volumes:
      - ./:/usr/src
    command: /bin/bash -c "npm run dev"
    ports:
      - 3000:3000
    tty: true